import type { Lang } from './wedding'

/**
 * 網站文案。zh 為正本，ja / en 依同一組 key 撰寫；
 * 少任何一個 key，TypeScript 會直接報錯。
 */
const zh = {
  langName: '中',
  common: {
    tbd: '待確認',
    toBeAdded: '待補',
    confirmed: '已確定',
    draft: '文案草稿・可再修改',
    draftShrine: '文案草稿・待神社確認',
  },
  nav: {
    invitation: '邀請函',
    ceremony: '儀式',
    timeline: '流程',
    venue: '神社',
    access: '交通',
    flights: '航班',
    stay: '住宿',
    faq: '指南',
    gift: '禮餅',
    contact: '回覆',
    menu: '目錄',
  },
  hero: {
    shrineLine: '神田明神　神前式',
    dateNote: '正確日期待確認・倒數屆時啟用',
    photoPlaceholder: '合照／神田明神實景',
    photoTag: '暫以此圖代替・合照待補',
    photoAlt: '浮世繪：二代歌川広重《東都三十六景・神田明神》',
    scroll: '邀請函',
    days: 'DAYS',
    hours: 'HRS',
    minutes: 'MIN',
    seconds: 'SEC',
  },
  invitation: {
    kicker: 'INVITATION',
    title: '邀請函',
    eyebrow: 'TO OUR DEAREST',
    heading: '一封來自東京的邀請',
    body: [
      '我們將在東京・神田明神，以一場神前式，許下彼此的約定。',
      '這一次，想給你一個安排旅行的理由——飛一趟東京，在春天的神社境內，陪我們完成這場安靜而慎重的儀式。',
      '不收禮金，也請不必準備禮物；你願意出席，就是最大的禮物。',
      '儀式之後，我們在境內的明神会館備了一席，想和你好好吃頓飯、慢慢說說話，再各自散去。',
      '期待在神田明神，與你見面。',
    ],
    signature: '敬邀',
  },
  ceremony: {
    kicker: 'CEREMONY DETAILS',
    title: '神前式資訊',
    dateLabel: 'DATE',
    timeLabel: 'TIME',
    venueLabel: 'VENUE',
    timeSub: '神前式開始時間',
    ritualTitle: '儀式內容',
    rituals: [
      { name: '參進之儀', desc: '在神職奏起的雅樂聲中，新人與列席的各位一同列隊，步向總朱漆塗的社殿。' },
      { name: '雅樂生演奏', desc: '儀式全程由樂人現場演奏雅樂相伴。' },
      { name: '巫女舞（豐榮之舞）', desc: '巫女隨樂人的演奏奉納祝舞，為兩人與在場親友祈福。' },
    ],
    orderTitle: '儀式流程',
    order: [
      '參進之儀',
      '修祓',
      '祝詞奏上',
      '巫女舞（豐榮之舞）',
      '誓盃之儀',
      '誓詞奉讀',
      '結び石之儀',
      '親族盃',
      '玉串拜禮',
      '齋主致詞',
    ],
    capacity: '進社殿參列的上限為 84 名（親族最多 48 名、朋友最多 36 名）——這與披露宴會場的容納人數是兩回事。',
    ritualSource: '儀式流程與參列人數依明神会館（神田明神 結婚式）官方網站',
    receptionTitle: '披露宴',
    receptionDesc: '境內合影之後，移步明神会館的「彩の間」用餐。',
    receptionHallLabel: '會場',
    receptionCuisineLabel: '料理',
    receptionTimeLabel: '開始時間',
    receptionSiteButton: '明神会館 披露宴會場介紹',
  },
  timeline: {
    kicker: 'WEDDING DAY',
    title: '當日流程',
    note: '賓客請留意 11:00 的神前式與 12:30 開始的披露宴。集合時間與散會時間確定後會再通知。',
    items: [
      { name: '新娘梳化', desc: '白無垢著裝與妝髮' },
      { name: '新郎梳化', desc: '紋付袴著裝與整裝' },
      { name: '親友集合', desc: '集合地點與時間確認後公布' },
      { name: '參進之儀', desc: '列隊步入御社殿' },
      { name: '神前式', desc: '雅樂・巫女舞・誓詞' },
      { name: '集合照・境內拍攝', desc: '全體合影與境內留影，約 30 分鐘' },
      { name: '披露宴', desc: '移步明神会館「彩の間」，一起吃頓飯' },
      { name: '散會', desc: '之後的東京時間，就留給你自己了' },
    ],
  },
  venue: {
    kicker: 'THE SHRINE',
    title: '神田明神',
    photoPlaceholder: '神社照片・待補',
    photoAlt: '神田明神 御社殿',
    aboutTitle: '關於神田明神',
    about: [
      '神田明神創建於天平二年（730 年），最初座落在武藏國豐島郡芝崎村——也就是今天千代田區大手町、將門塚一帶。',
      '元和二年（1616 年），神社遷到現在這片高地，鎮守江戶城的表鬼門，社殿由幕府興建。整個江戶時代，這裡被稱作「江戶總鎮守」；氏子地域至今仍涵蓋神田、日本橋、秋葉原、大手丸之內等一百零八個町會。',
      '現在的社殿建於昭和九年（1934 年）。大正十二年的關東大震災燒毀了江戶後期的社殿之後，重建時採用當時相當前衛的鋼骨鋼筋混凝土，外覆總朱漆塗；也正因為是耐火構造，戰火中境內多數建築付之一炬，社殿卻只受了輕微損傷，留存至今。',
    ],
    deitiesTitle: '御祭神',
    deities: [
      { name: '一之宮　大己貴命', alias: 'だいこく様', role: '國土經營、夫婦和合・結緣之神' },
      { name: '二之宮　少彥名命', alias: 'えびす様', role: '商業繁盛、醫藥健康、開運招福之神' },
      { name: '三之宮　平將門命', alias: 'まさかど様', role: '除災解厄之神' },
    ],
    aboutSource: '沿革與御祭神依神田明神官方網站',
    videoTitle: '看看神前式的樣子',
    videoDesc: '明神会館提供的影片，讓你在正式出席前，先感受一下神前式的氛圍與流程。',
    addressTitle: '所在地',
    addressLabel: 'ADDRESS',
    mapButton: '在 Google Maps 開啟',
    officialButton: '神社官方網站',
    addressSource: '地址與交通資訊依神田明神官方網站',
    noticeTitle: '參列提醒',
    notices: [
      '部分流程可能於戶外進行，建議準備一件外套。',
      '春季境內的參拜人潮與動線注意事項，待與神社確認後補充。',
    ],
    noticeTags: ['當日氣候與細節待確認', '待確認'],
  },
  access: {
    kicker: 'ACCESS',
    title: '交通方式',
    stationsTitle: '最近車站',
    walkUnit: (m: number) => `徒步 ${m} 分`,
    source: '站名・出口・步行時間依神田明神官方網站',
    videoTitle: '實地導覽影片',
    videoDesc: '我們自己在神田明神錄的導覽，帶你先走一遍怎麼進場、洗手間在哪裡。（影片為中文口說）',
    airportTitle: '從機場前往',
    routeSource: '時間與票價為 2026 年 8 月以 Google 地圖查得的參考值，實際依班次與購票方式而異，訂票前請再確認。',
    operatorLink: '業者官網',
    taxiTitle: '計程車建議',
    taxiDesc: '上車報「神田明神」即可；詳細建議待補',
  },
  flights: {
    kicker: 'FLIGHTS',
    title: '台灣前往東京',
    note: '2027 年 3 月已可訂位，但航空公司通常要更接近日期才會公布確切班表。以下是 2026 年 8 月查得的航線與航空公司，訂票時請以各官網當時公布的班表為準。',
    carriersLabel: '目前飛這條航線的航空公司',
    compareTitle: '羽田 vs 成田',
    compareDesc: '羽田離市中心近，到會場約 23–30 分鐘車程（不含轉乘）；成田較遠，Skyliner 到日暮里最短 36 分再轉 JR，N’EX 到東京站最快 53 分再轉 4 分。行李多又不想多走路的話，N’EX 轉中央線在御茶ノ水下車，是離神社最近的一站。',
    bookTitle: '訂票',
    bookNote: '航線與班次以各航空公司官網公告為準',
    dayNote: '婚禮當天有披露宴，結束時間會比原先預告的晚，請不要訂當天下午太早的回程班機。確切結束時間確定後會再通知。',
    japanTitle: '日本國內出發的親友',
    japanDesc: '不需要機票資訊——直接參考「交通方式」前往神田明神即可。',
  },
  stay: {
    kicker: 'STAY',
    title: '住宿建議',
    officialSite: '官方網站',
    criteria: '只列出「步行 10 分鐘內到會場，且離車站 10 分鐘內」的飯店；再遠的就不放了，免得當天奔波。',
    walkToVenue: '到會場',
    minUnit: '分',
    stationLabel: '最近車站',
    walkSource: '到會場的步行時間與距離皆為地圖路線估算；離車站的分鐘數為各飯店官網標示。房價與空房請直接至各飯店官網查詢。',
  },
  faq: {
    kicker: 'GUIDE · FAQ',
    title: '參列指南',
    note: '題目可再增減，答案取得後逐題展開。',
    items: [
      {
        q: '服裝建議',
        a: '以正式服裝為主；部分流程可能於戶外進行，建議準備一件外套。詳細建議（含女士鞋履、和裝租借等）之後補上。',
        status: 'draft' as const,
      },
      { q: '需要準備禮金嗎', a: '不需要。我們不收禮金，也不必準備禮物——你願意出席，就是最大的禮物。', status: 'answered' as const },
      { q: '儀式後有用餐嗎', a: '有的。境內合影之後，我們會移步到神田明神境內的明神会館「彩の間」用餐。開始時間確定後會再告訴大家。', status: 'answered' as const },
      { q: '神社參列禮儀', a: null, status: 'pending' as const },
      { q: '儀式中的攝影規範', a: '社殿內請勿拍攝——儀式中只有神田明神專屬攝影師可以拍照。披露宴期間則可以自由拍攝。', status: 'answered' as const },
      { q: '兒童可以參加嗎', a: '可以。會場備有依年齡準備的兒童餐，也有哺乳室。嬰兒車在館內可以使用，但社殿內不能推入，可寄放在衣帽間。', status: 'answered' as const },
      { q: '語言與翻譯', a: null, status: 'pending' as const },
    ],
    pendingTag: '待確認',
    shrineTag: '依神社規定・待確認',
  },
  gift: {
    kicker: 'WEDDING GIFT',
    title: '禮餅',
    chosen: '已 選 定',
    desc: [
      '來自東京、以「甜點花店」為概念的洋菓子品牌。',
      '招牌「鬱金香玫瑰」以鬱金香造型的貓舌餅乾，捧著一朵玫瑰花形的柔滑奶油餡，像一束可以吃的花。',
    ],
    rows: [
      { label: '禮盒品項與內容', tag: '待選定' },
      { label: '發放方式（台灣寄送或現場致贈）', tag: '待確認' },
    ],
  },
  contact: {
    kicker: 'RSVP · CONTACT',
    title: '出席回覆',
    formIntro: '為了統計人數與安排細節，屆時請透過表單告訴我們：',
    fields: ['是否出席', '同行人數', '飲食禁忌與過敏', '住宿需求'],
    rsvpButton: '回覆出席・RSVP',
    formTbd: 'Google 表單・連結待補',
    contactTitle: '聯絡我們',
    contactIntro: '不方便用表單的話，LINE 或 Email 回覆出席也可以。',
    lineTbd: '加入方式待補',
    emailTbd: '信箱待補',
    noPhone: '網站上不公開電話號碼',
    tagline: '期待在東京，與你共赴一場春日的約定',
  },
}

export type Copy = typeof zh

const ja: Copy = {
  langName: '日',
  common: {
    tbd: '未定',
    toBeAdded: '後日掲載',
    confirmed: '決定',
    draft: '文案は下書き・変更の可能性あり',
    draftShrine: '下書き・神社に確認中',
  },
  nav: {
    invitation: '招待状',
    ceremony: '挙式',
    timeline: '当日',
    venue: '神社',
    access: 'アクセス',
    flights: '航空便',
    stay: '宿泊',
    faq: 'ご案内',
    gift: '引菓子',
    contact: 'ご返信',
    menu: '目次',
  },
  hero: {
    shrineLine: '神田明神　神前式',
    dateNote: '日取りは未定・確定後にカウントダウンを開始します',
    photoPlaceholder: '二人の写真／神田明神の風景',
    photoTag: '仮の画像です・写真は後日',
    photoAlt: '浮世絵：二代歌川広重「東都三十六景・神田明神」',
    scroll: '招待状',
    days: 'DAYS',
    hours: 'HRS',
    minutes: 'MIN',
    seconds: 'SEC',
  },
  invitation: {
    kicker: 'INVITATION',
    title: '招待状',
    eyebrow: 'TO OUR DEAREST',
    heading: '東京からの、一通の招待',
    body: [
      '私たちは東京・神田明神にて、神前式を挙げます。',
      '今回は、旅の理由をひとつ差し上げたいのです——東京へ飛んで、春の境内で、この静かで厳かな儀式に立ち会っていただけたら。',
      'ご祝儀もお品も、どうかお気遣いなく。ご出席そのものが、いちばんの贈り物です。',
      '挙式のあとは、境内の明神会館にささやかな席をご用意しました。ゆっくりお食事をご一緒しながら、お話しできたらうれしいです。',
      '神田明神で、お会いできるのを楽しみにしています。',
    ],
    signature: 'より',
  },
  ceremony: {
    kicker: 'CEREMONY DETAILS',
    title: '神前式について',
    dateLabel: 'DATE',
    timeLabel: 'TIME',
    venueLabel: 'VENUE',
    timeSub: '挙式開始時刻',
    ritualTitle: '儀式の内容',
    rituals: [
      { name: '参進の儀', desc: '神職の奏でる雅楽の音色とともに、新郎新婦とご列席の皆様の想いを込めて、総朱塗りの社殿へ進みます。' },
      { name: '雅楽生演奏', desc: '式は雅楽の生演奏とともに執り行われます。' },
      { name: '巫女舞（豊栄の舞）', desc: '楽人の演奏により、巫女がお祝いの舞を奉奏します。' },
    ],
    orderTitle: '式次第',
    order: [
      '参進の儀',
      '修祓',
      '祝詞奏上',
      '巫女舞（豊栄の舞）',
      '誓盃の儀',
      '誓詞奉読',
      '結び石の儀',
      '親族盃',
      '玉串拝礼',
      '斎主挨拶',
    ],
    capacity: '社殿にご参列いただけるのは最大84名（ご親族〜48名・ご友人〜36名）。披露宴会場の収容人数とは別のものです。',
    ritualSource: '式次第と参列人数は明神会館（神田明神の結婚式）公式サイトに準拠',
    receptionTitle: '披露宴',
    receptionDesc: '境内での記念撮影ののち、明神会館「彩の間」へ移動してお食事です。',
    receptionHallLabel: '会場',
    receptionCuisineLabel: 'お料理',
    receptionTimeLabel: '開宴',
    receptionSiteButton: '明神会館 披露宴会場のご案内',
  },
  timeline: {
    kicker: 'WEDDING DAY',
    title: '当日の流れ',
    note: 'ご参列の皆様は11時の神前式と12時30分開宴の披露宴にご注目ください。集合時刻とお開きの時刻は決まり次第お知らせします。',
    items: [
      { name: '新婦 支度', desc: '白無垢の着付けとヘアメイク' },
      { name: '新郎 支度', desc: '紋付袴の着付け' },
      { name: '参列者 集合', desc: '集合場所と時刻は確認後にお知らせします' },
      { name: '参進の儀', desc: '列をなして御社殿へ' },
      { name: '神前式', desc: '雅楽・巫女舞・誓詞' },
      { name: '集合写真・境内撮影', desc: '全員での記念撮影と境内での撮影（約30分）' },
      { name: '披露宴', desc: '明神会館「彩の間」へ移動してお食事' },
      { name: 'お開き', desc: 'そのあとの東京の時間は、どうぞご自由に' },
    ],
  },
  venue: {
    kicker: 'THE SHRINE',
    title: '神田明神',
    photoPlaceholder: '神社の写真・後日掲載',
    photoAlt: '神田明神 御社殿',
    aboutTitle: '神田明神について',
    about: [
      '神田明神の創建は天平2年（730年）。出雲氏族の真神田臣によって、武蔵国豊島郡芝崎村——いまの千代田区大手町・将門塚のあたりに創建されました。',
      '元和2年（1616年）、江戸城の表鬼門を守る現在の地へ遷座し、幕府によって社殿が造営されます。江戸時代を通じて「江戸総鎮守」として崇敬を集め、氏子は神田・日本橋・秋葉原・大手丸の内など108町会に及びます。',
      '現在の社殿は昭和9年の再建。大正12年の関東大震災で江戸後期の社殿を焼失したのち、当時としては画期的な鉄骨鉄筋コンクリート・総朱漆塗で建て直されました。その耐火構造ゆえ、境内の多くが失われた戦災も、わずかな損傷で耐えぬいています。',
    ],
    deitiesTitle: '御祭神',
    deities: [
      { name: '一之宮　大己貴命', alias: 'だいこく様', role: '国土経営、夫婦和合・縁結びの神様' },
      { name: '二之宮　少彦名命', alias: 'えびす様', role: '商売繁昌、医薬健康、開運招福の神様' },
      { name: '三之宮　平将門命', alias: 'まさかど様', role: '除災厄除の神様' },
    ],
    aboutSource: '由緒・御祭神は神田明神公式サイトに準拠',
    videoTitle: '神前式の様子',
    videoDesc: '明神会館よりご提供いただいた映像です。当日の雰囲気を先取りしていただけます。',
    addressTitle: '所在地',
    addressLabel: 'ADDRESS',
    mapButton: 'Google マップで開く',
    officialButton: '神社公式サイト',
    addressSource: '住所・アクセスは神田明神公式サイトに準拠',
    noticeTitle: 'ご参列にあたって',
    notices: [
      '一部は屋外で執り行われる可能性があります。羽織るものをご用意ください。',
      '春の境内の混雑や動線については、神社に確認のうえ追記します。',
    ],
    noticeTags: ['当日の天候・詳細は未定', '未定'],
  },
  access: {
    kicker: 'ACCESS',
    title: 'アクセス',
    stationsTitle: '最寄り駅',
    walkUnit: (m: number) => `徒歩${m}分`,
    source: '駅名・出口・徒歩分数は神田明神公式サイトに準拠',
    videoTitle: '現地ガイド動画',
    videoDesc: '実際に神田明神を訪れて撮影した案内動画です。入り方やお手洗いの場所をご覧いただけます（中国語での説明です）。',
    airportTitle: '空港から',
    routeSource: '所要時間と運賃は2026年8月時点でGoogleマップにて検索した目安です。列車や購入方法により変わりますので、ご乗車前にご確認ください。',
    operatorLink: '公式サイト',
    taxiTitle: 'タクシーの場合',
    taxiDesc: '「神田明神」とお伝えください。詳細は後日',
  },
  flights: {
    kicker: 'FLIGHTS',
    title: '台湾から東京へ',
    note: '2027年3月の予約はすでに可能ですが、確定したダイヤは日程が近づいてから発表されるのが通例です。以下は2026年8月時点の就航路線と航空会社です。ご予約の際は各公式サイトの最新ダイヤをご確認ください。',
    carriersLabel: '現在この路線に就航している航空会社',
    compareTitle: '羽田 と 成田',
    compareDesc: '羽田は都心に近く、会場までおよそ23〜30分（乗換時間を除く）。成田は遠く、スカイライナーで日暮里まで最短36分＋JR、成田エクスプレスなら東京駅まで最速53分＋JR4分です。荷物が多く歩きたくない方は、成田エクスプレスから中央線に乗り換えて御茶ノ水で降りるのが、神社にいちばん近い駅です。',
    bookTitle: 'ご予約',
    bookNote: '就航路線・便数は各航空会社の公式サイトの案内に準じます',
    dayNote: '当日は披露宴がございますので、終了は当初のご案内より遅くなります。当日午後の早い便でのご帰国はお避けください。終了時刻は決まり次第お知らせします。',
    japanTitle: '日本国内からお越しの方',
    japanDesc: '航空便の情報は不要です。「アクセス」をご覧のうえ神田明神へお越しください。',
  },
  stay: {
    kicker: 'STAY',
    title: '宿泊について',
    officialSite: '公式サイト',
    criteria: '「会場まで徒歩10分以内、かつ最寄り駅から10分以内」の宿だけを載せています。当日の移動をできるだけ短くするためです。',
    walkToVenue: '会場まで',
    minUnit: '分',
    stationLabel: '最寄り駅',
    walkSource: '会場までの徒歩時間と距離は地図の徒歩ルートによる目安、駅からの分数は各ホテル公式サイトの表記です。料金・空室は各公式サイトでご確認ください。',
  },
  faq: {
    kicker: 'GUIDE · FAQ',
    title: 'ご参列の案内',
    note: '項目は増減する場合があります。回答が得られ次第、順次公開します。',
    items: [
      {
        q: '服装について',
        a: 'フォーマルな装いでお越しください。一部屋外での進行が想定されるため、羽織るものがあると安心です。詳細（履物、和装レンタルなど）は後日追記します。',
        status: 'draft' as const,
      },
      { q: 'ご祝儀は必要ですか', a: '不要です。ご祝儀もお品もお気遣いなく——ご出席そのものが、いちばんの贈り物です。', status: 'answered' as const },
      { q: '披露宴はありますか', a: 'はい。境内での記念撮影ののち、神田明神の境内にある明神会館「彩の間」でお食事をご用意しています。開宴時刻は決まり次第お知らせします。', status: 'answered' as const },
      { q: '神社での作法', a: null, status: 'pending' as const },
      { q: '式中の撮影について', a: '社殿内の撮影はご遠慮ください。挙式中は神田明神専属のフォトグラファーのみ撮影が可能です。披露宴中はご自由に撮影いただけます。', status: 'answered' as const },
      { q: '子ども連れでも大丈夫ですか', a: 'もちろんです。年齢に応じたお子様向けのお料理をご用意いただけます。授乳室もございます。ベビーカーは館内でご利用いただけますが、社殿内はご利用いただけないため、クロークでお預りいたします。', status: 'answered' as const },
      { q: '言語・通訳について', a: null, status: 'pending' as const },
    ],
    pendingTag: '未定',
    shrineTag: '神社の規定に準拠・確認中',
  },
  gift: {
    kicker: 'WEDDING GIFT',
    title: '引菓子',
    chosen: '決 定',
    desc: [
      '「甘くて香ばしいスイーツの花屋」をコンセプトにした、東京の洋菓子ブランド。',
      '看板商品「チューリップローズ」は、チューリップの形のラングドシャがバラの形のクリームを抱く、食べられる花束のようなお菓子です。',
    ],
    rows: [
      { label: '詰め合わせの内容', tag: '検討中' },
      { label: 'お渡し方法（台湾へ発送／当日手渡し）', tag: '未定' },
    ],
  },
  contact: {
    kicker: 'RSVP · CONTACT',
    title: 'ご出欠のご返信',
    formIntro: '人数と当日の手配のため、フォームからお知らせください：',
    fields: ['ご出欠', 'お連れ様の人数', '食物アレルギー・苦手な食材', '宿泊のご希望'],
    rsvpButton: 'ご出欠を送る・RSVP',
    formTbd: 'Google フォーム・リンクは後日',
    contactTitle: 'ご連絡先',
    contactIntro: 'フォームが難しい場合は、LINE か Email でも承ります。',
    lineTbd: '追加方法は後日',
    emailTbd: 'アドレスは後日',
    noPhone: '電話番号はサイト上では公開していません',
    tagline: '東京で、春の一日をご一緒できますように',
  },
}

const en: Copy = {
  langName: 'EN',
  common: {
    tbd: 'TBC',
    toBeAdded: 'Coming soon',
    confirmed: 'Confirmed',
    draft: 'Draft wording · may change',
    draftShrine: 'Draft · pending the shrine',
  },
  nav: {
    invitation: 'Invitation',
    ceremony: 'Ceremony',
    timeline: 'The day',
    venue: 'Shrine',
    access: 'Getting there',
    flights: 'Flights',
    stay: 'Stay',
    faq: 'Guide',
    gift: 'Favour',
    contact: 'RSVP',
    menu: 'Menu',
  },
  hero: {
    shrineLine: 'Kanda Myojin · Shinto Ceremony',
    dateNote: 'Exact date to be confirmed · countdown starts then',
    photoPlaceholder: 'Our photo / Kanda Myojin',
    photoTag: 'Stand-in image · our photo to come',
    photoAlt: 'Ukiyo-e print: Kanda Myojin, from Thirty-six Views of the Eastern Capital',
    scroll: 'Invitation',
    days: 'DAYS',
    hours: 'HRS',
    minutes: 'MIN',
    seconds: 'SEC',
  },
  invitation: {
    kicker: 'INVITATION',
    title: 'Invitation',
    eyebrow: 'TO OUR DEAREST',
    heading: 'An invitation from Tokyo',
    body: [
      'We are getting married at Kanda Myojin in Tokyo, in a traditional Shinto ceremony.',
      'Take this as your reason to book a trip — fly to Tokyo, stand with us in the shrine grounds in spring, and see us through a quiet, unhurried ceremony.',
      'No cash gifts, and please bring nothing else. You being there is the gift.',
      'Afterwards we have a table waiting at Myojin Kaikan, inside the shrine grounds — a proper meal, and time to talk, before we all go our separate ways.',
      'We cannot wait to see you at Kanda Myojin.',
    ],
    signature: '',
  },
  ceremony: {
    kicker: 'CEREMONY DETAILS',
    title: 'The ceremony',
    dateLabel: 'DATE',
    timeLabel: 'TIME',
    venueLabel: 'VENUE',
    timeSub: 'Ceremony start time',
    ritualTitle: 'What happens',
    rituals: [
      { name: 'Sanshin no gi — the procession', desc: 'To gagaku played by the priests, the couple and everyone attending walk in procession to the vermilion-lacquered hall.' },
      { name: 'Live gagaku', desc: 'The ceremony unfolds to gagaku, Japanese court music, played live.' },
      { name: 'Miko mai — Toyosaka no Mai', desc: 'A shrine maiden dances a blessing for the couple and everyone present, accompanied by the musicians.' },
    ],
    orderTitle: 'Order of ceremony',
    order: [
      'Procession to the hall',
      'Purification',
      'Reading of the prayer',
      'Shrine maiden\'s dance (Toyosaka no Mai)',
      'Sharing of sake',
      'Reading of the vows',
      'The tying-stone rite',
      'Cup shared with both families',
      'Offering of the sacred branch',
      'Closing words from the priest',
    ],
    capacity: 'Up to 84 people may attend inside the hall (family up to 48, friends up to 36) — a separate figure from the banquet room capacity.',
    ritualSource: 'Order of ceremony and capacity per the official Myojin Kaikan site',
    receptionTitle: 'Reception',
    receptionDesc: 'After the group photos we move to Sai-no-Ma at Myojin Kaikan for the meal.',
    receptionHallLabel: 'Room',
    receptionCuisineLabel: 'Food',
    receptionTimeLabel: 'Starts',
    receptionSiteButton: 'Myojin Kaikan — banquet halls',
  },
  timeline: {
    kicker: 'WEDDING DAY',
    title: 'The day',
    note: 'The times that matter for guests are the 11:00 ceremony and the 12:30 reception. We will confirm the gathering time and the finish time nearer the day.',
    items: [
      { name: 'Bride — hair, make-up, dressing', desc: 'Into the shiromuku' },
      { name: 'Groom — dressing', desc: 'Into the montsuki hakama' },
      { name: 'Guests gather', desc: 'Meeting point and time to be announced' },
      { name: 'Procession', desc: 'Walking in to the main hall' },
      { name: 'Shinto ceremony', desc: 'Gagaku, sacred dance, vows' },
      { name: 'Group photo in the grounds', desc: 'Everyone together, then photos around the shrine — about 30 minutes' },
      { name: 'Reception', desc: 'We move to Sai-no-Ma at Myojin Kaikan for the meal' },
      { name: 'We part ways', desc: 'The rest of Tokyo is yours' },
    ],
  },
  venue: {
    kicker: 'THE SHRINE',
    title: 'Kanda Myojin',
    photoPlaceholder: 'Shrine photo coming',
    photoAlt: 'The main hall of Kanda Myojin',
    aboutTitle: 'About the shrine',
    about: [
      'Kanda Myojin was founded in 730, on the site of what is now Otemachi in central Tokyo.',
      'In 1616 it moved to the hill it occupies today, placed there to guard the unlucky northeast gate of Edo Castle, with its hall built by the shogunate. Through the Edo period it was the guardian shrine of the whole city, and its parish still covers Kanda, Nihonbashi, Akihabara, Otemachi and Marunouchi — 108 neighbourhood associations in all.',
      'The present hall dates from 1934. After the Great Kanto Earthquake of 1923 destroyed its late-Edo predecessor, it was rebuilt in steel-reinforced concrete — radical for its time — and lacquered throughout in vermilion. Being fireproof, it survived the wartime air raids with only slight damage, while most of the grounds around it burned.',
    ],
    deitiesTitle: 'The deities',
    deities: [
      { name: 'Onamuchi-no-mikoto', alias: 'Daikoku-sama', role: 'God of nation-building, of marriage and of matchmaking' },
      { name: 'Sukunahikona-no-mikoto', alias: 'Ebisu-sama', role: 'God of business, health and good fortune' },
      { name: 'Taira-no-Masakado-no-mikoto', alias: 'Masakado-sama', role: 'God who wards off misfortune' },
    ],
    aboutSource: 'History and deities per the official Kanda Myojin website',
    videoTitle: 'What the ceremony looks like',
    videoDesc: 'A video from Myojin Kaikan, so you can get a feel for the day before you arrive.',
    addressTitle: 'Address',
    addressLabel: 'ADDRESS',
    mapButton: 'Open in Google Maps',
    officialButton: 'Shrine website',
    addressSource: 'Address and access per the official Kanda Myojin website',
    noticeTitle: 'Before you come',
    notices: [
      'Parts of the day may take place outdoors — a jacket is worth packing.',
      'Notes on spring crowds and moving around the grounds will follow, once the shrine confirms.',
    ],
    noticeTags: ['Weather and details TBC', 'TBC'],
  },
  access: {
    kicker: 'ACCESS',
    title: 'Getting there',
    stationsTitle: 'Nearest stations',
    walkUnit: (m: number) => `${m} min walk`,
    source: 'Station names, exits and walking times per the official shrine website',
    videoTitle: 'A quick walkthrough',
    videoDesc: 'We filmed this ourselves at Kanda Myojin — the way in, and where to find the restroom. (Narrated in Chinese.)',
    airportTitle: 'From the airport',
    routeSource: 'Times and fares are Google Maps estimates from August 2026; they vary by service and ticket type, so do check before you travel.',
    operatorLink: 'Operator site',
    taxiTitle: 'By taxi',
    taxiDesc: 'Just say "Kanda Myojin". More detail to follow.',
  },
  flights: {
    kicker: 'FLIGHTS',
    title: 'Taiwan to Tokyo',
    note: 'March 2027 is already bookable, but airlines usually publish firm timetables closer to the date. Below are the routes and carriers as of August 2026 — check each airline\'s own timetable when you book.',
    carriersLabel: 'Airlines currently flying this route',
    compareTitle: 'Haneda or Narita',
    compareDesc: 'Haneda is close to the centre — roughly 23–30 minutes to the venue, transfers aside. Narita is further out: the Skyliner reaches Nippori in 36 minutes at best, and the N\'EX reaches Tokyo Station in 53, plus 4 more on the Chuo Line. With heavy bags, the N\'EX and then the Chuo Line to Ochanomizu puts you at the closest station to the shrine.',
    bookTitle: 'Booking',
    bookNote: 'Routes and schedules as published by each airline',
    dayNote: 'There is a reception on the day, so we will finish later than first announced — please avoid booking an early afternoon flight home. We will confirm the end time closer to the day.',
    japanTitle: 'Coming from within Japan',
    japanDesc: 'No flight details needed — see "Getting there" for the way to Kanda Myojin.',
  },
  stay: {
    kicker: 'STAY',
    title: 'Where to stay',
    officialSite: 'Official site',
    criteria: 'Only hotels within a 10-minute walk of the venue, and within 10 minutes of a station. Anything further isn\'t worth the trek on the day.',
    walkToVenue: 'To the venue',
    minUnit: 'min',
    stationLabel: 'Nearest station',
    walkSource: 'Walking times and distances to the venue are map estimates; times to the station are as stated by each hotel. Check rates and availability on each hotel\'s own site.',
  },
  faq: {
    kicker: 'GUIDE · FAQ',
    title: 'Guest guide',
    note: 'Questions may be added or dropped; answers appear as we get them.',
    items: [
      {
        q: 'What should I wear?',
        a: 'Formal dress. Parts of the day may be outdoors, so bring a jacket. More detail — shoes, kimono rental — to follow.',
        status: 'draft' as const,
      },
      { q: 'Should I bring a gift?', a: 'No. No cash gifts, nothing to buy — you being there is the gift.', status: 'answered' as const },
      { q: 'Is there a reception?', a: 'Yes. After the group photos we move to Sai-no-Ma at Myojin Kaikan, inside the shrine grounds, for the meal. We will confirm the start time closer to the day.', status: 'answered' as const },
      { q: 'Shrine etiquette', a: null, status: 'pending' as const },
      { q: 'Photography during the ceremony', a: 'Please do not photograph inside the main hall — only the shrine\'s own photographer may shoot during the ceremony. At the reception you are free to take photos.', status: 'answered' as const },
      { q: 'Can children come?', a: 'Yes. Children\'s meals are prepared to suit their age, and there is a nursing room. Strollers are fine inside the building but not in the main hall — the cloakroom will hold them for you.', status: 'answered' as const },
      { q: 'Language and translation', a: null, status: 'pending' as const },
    ],
    pendingTag: 'TBC',
    shrineTag: 'Per shrine rules · TBC',
  },
  gift: {
    kicker: 'WEDDING GIFT',
    title: 'Our gift to you',
    chosen: 'C H O S E N',
    desc: [
      'A Tokyo confectionery brand built on the idea of a sweet-scented flower shop.',
      'Its signature Tulip Rose is a tulip-shaped langue de chat cradling a rose of smooth cream — a bouquet you can eat.',
    ],
    rows: [
      { label: 'Which box and what is in it', tag: 'Deciding' },
      { label: 'How it reaches you (posted in Taiwan or handed over)', tag: 'TBC' },
    ],
  },
  contact: {
    kicker: 'RSVP · CONTACT',
    title: 'RSVP',
    formIntro: 'So we can plan numbers and details, the form will ask you for:',
    fields: ['Whether you can come', 'How many with you', 'Allergies or foods you avoid', 'Accommodation needs'],
    rsvpButton: 'RSVP',
    formTbd: 'Google Form · link coming',
    contactTitle: 'Contact us',
    contactIntro: 'If the form is awkward, LINE or email works just as well.',
    lineTbd: 'Details coming',
    emailTbd: 'Address coming',
    noPhone: 'We do not publish a phone number here',
    tagline: 'We hope to share a spring day with you in Tokyo',
  },
}

export const dict: Record<Lang, Copy> = { zh, ja, en }

export const langs: Lang[] = ['zh', 'ja', 'en']
