import type { Lang } from './wedding'

/**
 * 網站文案。zh 為正本，ja / en 依同一組 key 撰寫；
 * 少任何一個 key，TypeScript 會直接報錯。
 */
const zh = {
  langName: '中',
  common: {
    tbd: '待確認',
    toBeAdded: '待補',
    confirmed: '已確定',
    draft: '文案草稿・可再修改',
    draftShrine: '文案草稿・待神社確認',
  },
  nav: {
    invitation: '邀請函',
    ceremony: '儀式',
    timeline: '流程',
    venue: '神社',
    access: '交通',
    flights: '航班',
    stay: '住宿',
    faq: '指南',
    gift: '禮餅',
    contact: '回覆',
    menu: '目錄',
  },
  hero: {
    shrineLine: '神田明神　神前式',
    dateNote: '正確日期待確認・倒數屆時啟用',
    photoPlaceholder: '合照／神田明神實景',
    photoTag: '暫以此圖代替・合照待補',
    photoAlt: '浮世繪：二代歌川広重《東都三十六景・神田明神》',
    scroll: '邀請函',
    days: 'DAYS',
    hours: 'HRS',
    minutes: 'MIN',
    seconds: 'SEC',
  },
  invitation: {
    kicker: 'INVITATION',
    title: '邀請函',
    eyebrow: 'TO OUR DEAREST',
    heading: '一封來自東京的邀請',
    body: [
      '我們將在東京・神田明神，以一場神前式，許下彼此的約定。',
      '這一次，想給你一個安排旅行的理由——飛一趟東京，在春天的神社境內，陪我們完成這場安靜而慎重的儀式。',
      '不收禮金，也請不必準備禮物；你願意出席，就是最大的禮物。',
      '儀式後沒有安排會食——拍過合照，就把時間還給你，去過屬於你自己的東京。',
      '期待在神田明神，與你見面。',
    ],
    signature: '敬邀',
  },
  ceremony: {
    kicker: 'CEREMONY DETAILS',
    title: '神前式資訊',
    dateLabel: 'DATE',
    timeLabel: 'TIME',
    venueLabel: 'VENUE',
    timeSub: '神前式開始時間',
    ritualTitle: '儀式內容',
    rituals: [
      { name: '參進之儀', desc: '由神職與巫女引領，新人與親族列隊緩步走向御社殿。' },
      { name: '雅樂', desc: '儀式由日本傳統雅樂的樂音相伴進行。' },
      { name: '巫女舞', desc: '巫女奉納神樂舞，為兩人與在場親友祈福。' },
    ],
    receptionTitle: '披露宴／會食',
    receptionDesc: '儀式後不設會食；境內合影後散會，各自展開東京行程。',
  },
  timeline: {
    kicker: 'WEDDING DAY',
    title: '當日流程',
    note: '所有時間皆為佔位，待與神社確認後逐項填入公布。',
    items: [
      { name: '新郎新娘梳化', desc: '白無垢・紋付袴著裝與妝髮' },
      { name: '儀式前攝影', desc: '新人寫真與花絮拍攝' },
      { name: '親友集合', desc: '集合地點與時間確認後公布' },
      { name: '參進之儀', desc: '列隊步入御社殿' },
      { name: '神前式', desc: '雅樂・巫女舞・誓詞' },
      { name: '集合照・境內拍攝', desc: '全體合影與境內留影' },
      { name: '散會・各自的東京時間', desc: '不設會食——拍完合照就散會，歡迎在境內與我們多拍幾張' },
    ],
  },
  venue: {
    kicker: 'THE SHRINE',
    title: '神田明神',
    photoPlaceholder: '神社照片・待補',
    photoAlt: '神田明神 御社殿',
    aboutTitle: '關於神田明神',
    aboutDraft: '神社介紹文案・待撰寫。',
    aboutDraftSub: '預計涵蓋：神社簡介、御祭神、神前式在此舉行的意義；內容確認後補上。',
    addressTitle: '所在地',
    addressLabel: 'ADDRESS',
    mapButton: '在 Google Maps 開啟',
    officialButton: '神社官方網站',
    addressSource: '地址與交通資訊依神田明神官方網站',
    noticeTitle: '參列提醒',
    notices: [
      '部分流程可能於戶外進行，建議準備一件薄外套。',
      '春季境內的參拜人潮與動線注意事項，待與神社確認後補充。',
    ],
    noticeTags: ['當日氣候與細節待確認', '待確認'],
  },
  access: {
    kicker: 'ACCESS',
    title: '交通方式',
    stationsTitle: '最近車站',
    walkUnit: (m: number) => `徒步 ${m} 分`,
    source: '站名・出口・步行時間依神田明神官方網站',
    airportTitle: '從機場前往',
    haneda: '羽田機場 → 會場',
    narita: '成田機場 → 會場',
    routeTbd: '路線待補',
    airportNote: '轉乘路線與所需時間，待航班與住宿區域確定後一併整理。',
    taxiTitle: '計程車建議',
    taxiDesc: '上車報「神田明神」即可；詳細建議待補',
  },
  flights: {
    kicker: 'FLIGHTS',
    title: '台灣前往東京',
    note: '班表變動頻繁，這裡刻意不放班次；婚期確定後，再補上當時的建議航班。',
    flightTbd: '建議班次待補',
    compareTitle: '羽田 vs 成田',
    compareDesc: '羽田較靠近市中心；兩機場前往會場的交通時間與費用比較，待補。',
    compareTbd: '比較表待補',
    japanTitle: '日本國內出發的親友',
    japanDesc: '不需要機票資訊——直接參考「交通方式」前往神田明神即可。',
  },
  stay: {
    kicker: 'STAY',
    title: '住宿建議',
    nearest: '離會場最近',
    hotelTbd: '推薦飯店・待定',
    officialSite: '官方網站',
    walkSource: '步行時間為各飯店官網標示，僅供參考',
    areas: [
      { name: '御茶之水', desc: '步行即可抵達神田明神，儀式當天最輕鬆的選擇。' },
      { name: '秋葉原', desc: '距會場一站之遙，購物與美食選擇多，適合順道觀光。' },
      { name: '神田', desc: '商務飯店密集、價位相對友善的區域。' },
      { name: '東京站周邊', desc: '新幹線與機場交通樞紐，適合行程會延伸到其他城市的親友。' },
    ],
    note: '以下是鄰近會場的候選飯店，我們尚未指定推薦；房價與空房請直接至各飯店官網查詢。',
  },
  faq: {
    kicker: 'GUIDE · FAQ',
    title: '參列指南',
    note: '題目可再增減，答案取得後逐題展開。',
    items: [
      {
        q: '服裝建議',
        a: '以正式服裝為主；部分流程可能於戶外進行，建議準備一件薄外套。詳細建議（含女士鞋履、和裝租借等）之後補上。',
        status: 'draft' as const,
      },
      { q: '需要準備禮金嗎', a: '不需要。我們不收禮金，也不必準備禮物——你願意出席，就是最大的禮物。', status: 'answered' as const },
      { q: '會食的安排', a: '儀式後不設會食。在境內拍完合照後散會，把時間留給每個人自己的東京行程。', status: 'answered' as const },
      { q: '神社參列禮儀', a: null, status: 'pending' as const },
      { q: '儀式中的攝影規範', a: null, status: 'pending' as const },
      { q: '兒童可以參加嗎', a: null, status: 'pending' as const },
      { q: '語言與翻譯', a: null, status: 'pending' as const },
    ],
    pendingTag: '待確認',
    shrineTag: '依神社規定・待確認',
  },
  gift: {
    kicker: 'WEDDING GIFT',
    title: '禮餅',
    chosen: '已 選 定',
    desc: [
      '來自東京、以「甜點花店」為概念的洋菓子品牌。',
      '招牌「鬱金香玫瑰」以鬱金香造型的貓舌餅乾，捧著一朵玫瑰花形的柔滑奶油餡，像一束可以吃的花。',
    ],
    rows: [
      { label: '禮盒品項與內容', tag: '待選定' },
      { label: '發放方式（台灣寄送或現場致贈）', tag: '待確認' },
    ],
  },
  contact: {
    kicker: 'RSVP · CONTACT',
    title: '出席回覆',
    formIntro: '為了統計人數與安排細節，屆時請透過表單告訴我們：',
    fields: ['是否出席', '同行人數', '飲食禁忌', '住宿需求'],
    rsvpButton: '回覆出席・RSVP',
    formTbd: 'Google 表單・連結待補',
    contactTitle: '聯絡我們',
    contactIntro: '不方便用表單的話，LINE 或 Email 回覆出席也可以。',
    lineTbd: '加入方式待補',
    emailTbd: '信箱待補',
    noPhone: '網站上不公開電話號碼',
    tagline: '期待在東京，與你共赴一場春日的約定',
  },
}

export type Copy = typeof zh

const ja: Copy = {
  langName: '日',
  common: {
    tbd: '未定',
    toBeAdded: '後日掲載',
    confirmed: '決定',
    draft: '文案は下書き・変更の可能性あり',
    draftShrine: '下書き・神社に確認中',
  },
  nav: {
    invitation: '招待状',
    ceremony: '挙式',
    timeline: '当日',
    venue: '神社',
    access: 'アクセス',
    flights: '航空便',
    stay: '宿泊',
    faq: 'ご案内',
    gift: '引菓子',
    contact: 'ご返信',
    menu: '目次',
  },
  hero: {
    shrineLine: '神田明神　神前式',
    dateNote: '日取りは未定・確定後にカウントダウンを開始します',
    photoPlaceholder: '二人の写真／神田明神の風景',
    photoTag: '仮の画像です・写真は後日',
    photoAlt: '浮世絵：二代歌川広重「東都三十六景・神田明神」',
    scroll: '招待状',
    days: 'DAYS',
    hours: 'HRS',
    minutes: 'MIN',
    seconds: 'SEC',
  },
  invitation: {
    kicker: 'INVITATION',
    title: '招待状',
    eyebrow: 'TO OUR DEAREST',
    heading: '東京からの、一通の招待',
    body: [
      '私たちは東京・神田明神にて、神前式を挙げます。',
      '今回は、旅の理由をひとつ差し上げたいのです——東京へ飛んで、春の境内で、この静かで厳かな儀式に立ち会っていただけたら。',
      'ご祝儀もお品も、どうかお気遣いなく。ご出席そのものが、いちばんの贈り物です。',
      '式のあとに会食は設けません。記念写真を撮ったら、そのあとの時間はどうぞご自身の東京へ。',
      '神田明神で、お会いできるのを楽しみにしています。',
    ],
    signature: 'より',
  },
  ceremony: {
    kicker: 'CEREMONY DETAILS',
    title: '神前式について',
    dateLabel: 'DATE',
    timeLabel: 'TIME',
    venueLabel: 'VENUE',
    timeSub: '挙式開始時刻',
    ritualTitle: '儀式の内容',
    rituals: [
      { name: '参進の儀', desc: '神職と巫女に導かれ、新郎新婦と親族が列をなして御社殿へ進みます。' },
      { name: '雅楽', desc: '日本の伝統音楽である雅楽の調べとともに執り行われます。' },
      { name: '巫女舞', desc: '巫女が神楽舞を奉納し、二人と参列者の幸せを祈ります。' },
    ],
    receptionTitle: '披露宴／会食',
    receptionDesc: '式後の会食は設けません。境内での記念撮影ののち解散し、それぞれの東京へ。',
  },
  timeline: {
    kicker: 'WEDDING DAY',
    title: '当日の流れ',
    note: '時刻はすべて仮です。神社との確認後、順次公開します。',
    items: [
      { name: '新郎新婦 支度', desc: '白無垢・紋付袴の着付けとヘアメイク' },
      { name: '挙式前撮影', desc: '二人の写真とオフショット' },
      { name: '参列者 集合', desc: '集合場所と時刻は確認後にお知らせします' },
      { name: '参進の儀', desc: '列をなして御社殿へ' },
      { name: '神前式', desc: '雅楽・巫女舞・誓詞' },
      { name: '集合写真・境内撮影', desc: '全員での記念撮影と境内での撮影' },
      { name: '解散・それぞれの東京へ', desc: '会食はありません。写真を撮り終えたら解散、境内での撮影はご自由に' },
    ],
  },
  venue: {
    kicker: 'THE SHRINE',
    title: '神田明神',
    photoPlaceholder: '神社の写真・後日掲載',
    photoAlt: '神田明神 御社殿',
    aboutTitle: '神田明神について',
    aboutDraft: '神社紹介の文章・準備中。',
    aboutDraftSub: '御祭神、神社の由緒、ここで神前式を挙げる意味などを、確認のうえ掲載します。',
    addressTitle: '所在地',
    addressLabel: 'ADDRESS',
    mapButton: 'Google マップで開く',
    officialButton: '神社公式サイト',
    addressSource: '住所・アクセスは神田明神公式サイトに準拠',
    noticeTitle: 'ご参列にあたって',
    notices: [
      '一部は屋外で執り行われる可能性があります。羽織るものをご用意ください。',
      '春の境内の混雑や動線については、神社に確認のうえ追記します。',
    ],
    noticeTags: ['当日の天候・詳細は未定', '未定'],
  },
  access: {
    kicker: 'ACCESS',
    title: 'アクセス',
    stationsTitle: '最寄り駅',
    walkUnit: (m: number) => `徒歩${m}分`,
    source: '駅名・出口・徒歩分数は神田明神公式サイトに準拠',
    airportTitle: '空港から',
    haneda: '羽田空港 → 会場',
    narita: '成田空港 → 会場',
    routeTbd: '経路は後日',
    airportNote: '乗換経路と所要時間は、航空便と宿泊エリアの確定後にまとめます。',
    taxiTitle: 'タクシーの場合',
    taxiDesc: '「神田明神」とお伝えください。詳細は後日',
  },
  flights: {
    kicker: 'FLIGHTS',
    title: '台湾から東京へ',
    note: 'ダイヤは変わりやすいため、便名はあえて載せていません。日取りの確定後に候補を掲載します。',
    flightTbd: '便の候補は後日',
    compareTitle: '羽田 と 成田',
    compareDesc: '羽田のほうが都心に近い立地です。会場までの所要時間と費用の比較は後日。',
    compareTbd: '比較表は後日',
    japanTitle: '日本国内からお越しの方',
    japanDesc: '航空便の情報は不要です。「アクセス」をご覧のうえ神田明神へお越しください。',
  },
  stay: {
    kicker: 'STAY',
    title: '宿泊について',
    nearest: '会場から徒歩圏',
    hotelTbd: 'おすすめの宿・検討中',
    officialSite: '公式サイト',
    walkSource: '徒歩分数は各ホテル公式サイトの表記です',
    areas: [
      { name: '御茶ノ水', desc: '神田明神まで歩ける距離。当日いちばん負担の少ない選択です。' },
      { name: '秋葉原', desc: '会場から一駅。買い物にも食事にも困りません。' },
      { name: '神田', desc: 'ビジネスホテルが多く、価格も比較的手頃なエリア。' },
      { name: '東京駅周辺', desc: '新幹線と空港アクセスの拠点。他都市へ足をのばす方に。' },
    ],
    note: '会場周辺の候補です。まだ一軒に絞ってはいません。料金と空室は各公式サイトでご確認ください。',
  },
  faq: {
    kicker: 'GUIDE · FAQ',
    title: 'ご参列の案内',
    note: '項目は増減する場合があります。回答が得られ次第、順次公開します。',
    items: [
      {
        q: '服装について',
        a: 'フォーマルな装いでお越しください。一部屋外での進行が想定されるため、羽織るものがあると安心です。詳細（履物、和装レンタルなど）は後日追記します。',
        status: 'draft' as const,
      },
      { q: 'ご祝儀は必要ですか', a: '不要です。ご祝儀もお品もお気遣いなく——ご出席そのものが、いちばんの贈り物です。', status: 'answered' as const },
      { q: '会食はありますか', a: '式後の会食は設けません。境内で写真を撮ったのち解散し、そのあとの時間はご自身の東京へ。', status: 'answered' as const },
      { q: '神社での作法', a: null, status: 'pending' as const },
      { q: '式中の撮影について', a: null, status: 'pending' as const },
      { q: '子ども連れでも大丈夫ですか', a: null, status: 'pending' as const },
      { q: '言語・通訳について', a: null, status: 'pending' as const },
    ],
    pendingTag: '未定',
    shrineTag: '神社の規定に準拠・確認中',
  },
  gift: {
    kicker: 'WEDDING GIFT',
    title: '引菓子',
    chosen: '決 定',
    desc: [
      '「甘くて香ばしいスイーツの花屋」をコンセプトにした、東京の洋菓子ブランド。',
      '看板商品「チューリップローズ」は、チューリップの形のラングドシャがバラの形のクリームを抱く、食べられる花束のようなお菓子です。',
    ],
    rows: [
      { label: '詰め合わせの内容', tag: '検討中' },
      { label: 'お渡し方法（台湾へ発送／当日手渡し）', tag: '未定' },
    ],
  },
  contact: {
    kicker: 'RSVP · CONTACT',
    title: 'ご出欠のご返信',
    formIntro: '人数と当日の手配のため、フォームからお知らせください：',
    fields: ['ご出欠', 'お連れ様の人数', '食物アレルギー等', '宿泊のご希望'],
    rsvpButton: 'ご出欠を送る・RSVP',
    formTbd: 'Google フォーム・リンクは後日',
    contactTitle: 'ご連絡先',
    contactIntro: 'フォームが難しい場合は、LINE か Email でも承ります。',
    lineTbd: '追加方法は後日',
    emailTbd: 'アドレスは後日',
    noPhone: '電話番号はサイト上では公開していません',
    tagline: '東京で、春の一日をご一緒できますように',
  },
}

const en: Copy = {
  langName: 'EN',
  common: {
    tbd: 'TBC',
    toBeAdded: 'Coming soon',
    confirmed: 'Confirmed',
    draft: 'Draft wording · may change',
    draftShrine: 'Draft · pending the shrine',
  },
  nav: {
    invitation: 'Invitation',
    ceremony: 'Ceremony',
    timeline: 'The day',
    venue: 'Shrine',
    access: 'Getting there',
    flights: 'Flights',
    stay: 'Stay',
    faq: 'Guide',
    gift: 'Gift',
    contact: 'RSVP',
    menu: 'Menu',
  },
  hero: {
    shrineLine: 'Kanda Myojin · Shinto Ceremony',
    dateNote: 'Exact date to be confirmed · countdown starts then',
    photoPlaceholder: 'Our photo / Kanda Myojin',
    photoTag: 'Stand-in image · our photo to come',
    photoAlt: 'Ukiyo-e print: Kanda Myojin, from Thirty-six Views of the Eastern Capital',
    scroll: 'Invitation',
    days: 'DAYS',
    hours: 'HRS',
    minutes: 'MIN',
    seconds: 'SEC',
  },
  invitation: {
    kicker: 'INVITATION',
    title: 'Invitation',
    eyebrow: 'TO OUR DEAREST',
    heading: 'An invitation from Tokyo',
    body: [
      'We are getting married at Kanda Myojin in Tokyo, in a traditional Shinto ceremony.',
      'Take this as your reason to book a trip — fly to Tokyo, stand with us in the shrine grounds in spring, and see us through a quiet, unhurried ceremony.',
      'No cash gifts, and please bring nothing else. You being there is the gift.',
      'There is no reception afterwards — once we have taken photos together, the rest of the day is yours to spend in Tokyo.',
      'We cannot wait to see you at Kanda Myojin.',
    ],
    signature: '',
  },
  ceremony: {
    kicker: 'CEREMONY DETAILS',
    title: 'The ceremony',
    dateLabel: 'DATE',
    timeLabel: 'TIME',
    venueLabel: 'VENUE',
    timeSub: 'Ceremony start time',
    ritualTitle: 'What happens',
    rituals: [
      { name: 'Sanshin no gi', desc: 'Led by priests and shrine maidens, the couple and family walk in procession to the main hall.' },
      { name: 'Gagaku', desc: 'The ceremony unfolds to gagaku, Japanese traditional court music.' },
      { name: 'Miko mai', desc: 'A shrine maiden performs a sacred dance, a blessing for the couple and everyone present.' },
    ],
    receptionTitle: 'Reception',
    receptionDesc: 'There is no reception. After group photos in the shrine grounds we part ways, and the day is yours.',
  },
  timeline: {
    kicker: 'WEDDING DAY',
    title: 'The day',
    note: 'Every time below is a placeholder, to be filled in once the shrine confirms.',
    items: [
      { name: 'Hair, make-up and dressing', desc: 'Shiromuku and montsuki hakama' },
      { name: 'Pre-ceremony photos', desc: 'Portraits and candids' },
      { name: 'Guests gather', desc: 'Meeting point and time to be announced' },
      { name: 'Procession', desc: 'Walking in to the main hall' },
      { name: 'Shinto ceremony', desc: 'Gagaku, sacred dance, vows' },
      { name: 'Group photo in the grounds', desc: 'Everyone together, then photos around the shrine' },
      { name: 'We part ways', desc: 'No reception — once the photos are done, the rest of Tokyo is yours' },
    ],
  },
  venue: {
    kicker: 'THE SHRINE',
    title: 'Kanda Myojin',
    photoPlaceholder: 'Shrine photo coming',
    photoAlt: 'The main hall of Kanda Myojin',
    aboutTitle: 'About the shrine',
    aboutDraft: 'Introduction to the shrine — being written.',
    aboutDraftSub: 'It will cover the shrine, its deities, and what a ceremony here means to us. Added once confirmed.',
    addressTitle: 'Address',
    addressLabel: 'ADDRESS',
    mapButton: 'Open in Google Maps',
    officialButton: 'Shrine website',
    addressSource: 'Address and access per the official Kanda Myojin website',
    noticeTitle: 'Before you come',
    notices: [
      'Parts of the day may take place outdoors — a light jacket is worth packing.',
      'Notes on spring crowds and moving around the grounds will follow, once the shrine confirms.',
    ],
    noticeTags: ['Weather and details TBC', 'TBC'],
  },
  access: {
    kicker: 'ACCESS',
    title: 'Getting there',
    stationsTitle: 'Nearest stations',
    walkUnit: (m: number) => `${m} min walk`,
    source: 'Station names, exits and walking times per the official shrine website',
    airportTitle: 'From the airport',
    haneda: 'Haneda → the shrine',
    narita: 'Narita → the shrine',
    routeTbd: 'Route coming',
    airportNote: 'Connections and journey times will be written up once flights and hotels are settled.',
    taxiTitle: 'By taxi',
    taxiDesc: 'Just say "Kanda Myojin". More detail to follow.',
  },
  flights: {
    kicker: 'FLIGHTS',
    title: 'Taiwan to Tokyo',
    note: 'Schedules change often, so no flight numbers here on purpose. Suggested flights once the date is fixed.',
    flightTbd: 'Suggested flights coming',
    compareTitle: 'Haneda or Narita',
    compareDesc: 'Haneda sits closer to central Tokyo. A comparison of time and cost to the shrine will follow.',
    compareTbd: 'Comparison coming',
    japanTitle: 'Coming from within Japan',
    japanDesc: 'No flight details needed — see "Getting there" for the way to Kanda Myojin.',
  },
  stay: {
    kicker: 'STAY',
    title: 'Where to stay',
    nearest: 'Closest to the shrine',
    hotelTbd: 'Hotel picks to come',
    officialSite: 'Official site',
    walkSource: 'Walking times as stated on each hotel\'s own site',
    areas: [
      { name: 'Ochanomizu', desc: 'Walking distance to Kanda Myojin — the easiest choice on the day.' },
      { name: 'Akihabara', desc: 'One stop away, with plenty of food and shopping around it.' },
      { name: 'Kanda', desc: 'Dense with business hotels, and gentler on the wallet.' },
      { name: 'Tokyo Station', desc: 'The hub for shinkansen and airport transfers, if your trip goes further.' },
    ],
    note: 'These are candidates near the venue — we have not narrowed it down. Check rates and availability on each hotel\'s own site.',
  },
  faq: {
    kicker: 'GUIDE · FAQ',
    title: 'Guest guide',
    note: 'Questions may be added or dropped; answers appear as we get them.',
    items: [
      {
        q: 'What should I wear?',
        a: 'Formal dress. Parts of the day may be outdoors, so bring a light jacket. More detail — shoes, kimono rental — to follow.',
        status: 'draft' as const,
      },
      { q: 'Should I bring a gift?', a: 'No. No cash gifts, nothing to buy — you being there is the gift.', status: 'answered' as const },
      { q: 'Is there a reception?', a: 'No. We take photos in the shrine grounds and then part ways, so the rest of the day is yours.', status: 'answered' as const },
      { q: 'Shrine etiquette', a: null, status: 'pending' as const },
      { q: 'Photography during the ceremony', a: null, status: 'pending' as const },
      { q: 'Can children come?', a: null, status: 'pending' as const },
      { q: 'Language and translation', a: null, status: 'pending' as const },
    ],
    pendingTag: 'TBC',
    shrineTag: 'Per shrine rules · TBC',
  },
  gift: {
    kicker: 'WEDDING GIFT',
    title: 'Wedding gift',
    chosen: 'C H O S E N',
    desc: [
      'A Tokyo confectionery brand built on the idea of a sweet-scented flower shop.',
      'Its signature Tulip Rose is a tulip-shaped langue de chat cradling a rose of smooth cream — a bouquet you can eat.',
    ],
    rows: [
      { label: 'Which box and what is in it', tag: 'Deciding' },
      { label: 'How it reaches you (posted in Taiwan or handed over)', tag: 'TBC' },
    ],
  },
  contact: {
    kicker: 'RSVP · CONTACT',
    title: 'RSVP',
    formIntro: 'So we can plan numbers and details, the form will ask you for:',
    fields: ['Whether you can come', 'How many with you', 'Dietary needs', 'Accommodation needs'],
    rsvpButton: 'RSVP',
    formTbd: 'Google Form · link coming',
    contactTitle: 'Contact us',
    contactIntro: 'If the form is awkward, LINE or email works just as well.',
    lineTbd: 'Details coming',
    emailTbd: 'Address coming',
    noPhone: 'We do not publish a phone number here',
    tagline: 'We hope to share a spring day with you in Tokyo',
  },
}

export const dict: Record<Lang, Copy> = { zh, ja, en }

export const langs: Lang[] = ['zh', 'ja', 'en']
